In [1]:
#library imports
import pandas as pd
import numpy as np
import os
import datetime
from datetime import date
import matplotlib.pyplot as plt
from array import array
from scipy import stats

In [6]:
#get working directory
cwd = os.getcwd()
print(cwd)

C:\Users\ssi2309.60050\Downloads

In [7]:
#setting directories (order = old to new)
dir_20230331 = '~\\Downloads\\results_230331' #2023 March
dir_20230421 = '~\\Downloads\\results_230421_new3' #2023 Apr
dir_20230720 = '~\\Downloads\\results_230720_new' #2023 July
dir_20230830 = '~\\Downloads\\results_230830_new' #2023 Aug
#all_230928.zip â†’ not found, only have 08-09-2023 and 30-08-2023
dir_20231124 = '~\\Downloads\\results_231124' #2023 Nov 24th
dir_20231129 = '~\\Downloads\\results_231129' #(after a vocab update)
dir_20231206 = '~\\Downloads\\results_231206' #2023 Dec
dir_20240112 = '~\\Downloads\\results 120124' #2024 Jan 
dir_20240201 = '~\\Downloads\\results_240201' #2024 Feb 1st
dir_20240219 = '~\\Downloads\\results_240219' #2024 Feb 19th
dir_20240325 = '~\\Downloads\\results_250324' #2024 March 25th

## Table counts analysis

In [8]:
#reading in the table counts
march23_table_counts_df = pd.read_csv(f'{dir_20230331}\\countstables.csv')
apr23_table_counts_df = pd.read_csv(f'{dir_20230421}\\countstables.csv')
jul23_table_counts_df = pd.read_csv(f'{dir_20230720}\\countstables.csv')
aug23_table_counts_df = pd.read_csv(f'{dir_20230830}\\countstables.csv')
nov2324_table_counts_df = pd.read_csv(f'{dir_20231124}\\countstables.csv')
nov2329_table_counts_df = pd.read_csv(f'{dir_20231129}\\countstables.csv')
dec23_table_counts_df = pd.read_csv(f'{dir_20231206}\\countstables.csv')
jan24_table_counts_df = pd.read_csv(f'{dir_20240112}\\countstables.csv')
feb2401_table_counts_df = pd.read_csv(f'{dir_20240201}\\countstables.csv')
feb2419_table_counts_df = pd.read_csv(f'{dir_20240219}\\countstables.csv')
march24_table_counts_df = pd.read_csv(f'{dir_20240325}\\countstables.csv')


#setting df names as table_date
march23_table_counts_df.name = 'table_20230331'
apr23_table_counts_df.name = 'table_20230421'
jul23_table_counts_df.name = 'table_20230720'
aug23_table_counts_df.name = 'table_20230830'
nov2324_table_counts_df.name = 'table_20231124'
nov2329_table_counts_df.name = 'table_20231129'
dec23_table_counts_df.name = 'table_20231206'
jan24_table_counts_df.name = 'table_20240112'
feb2401_table_counts_df.name = 'table_20240201'
feb2419_table_counts_df.name = 'table_20240219'
march24_table_counts_df.name= 'table_20240325'

In [9]:
#function to clean a table counts df
def clean_table_counts(df):
    #get the name of the df and drop _table_counts_df
    name_date = df.name
    count_date = name_date.replace('table_','count_')
    
    #drop irrelevant and duplicate columns
    clean_df = df.drop(columns = ["CountsID","ConceptID", "ValueConceptID"])
    
    #rename count columns for clarity
    clean_df = clean_df.rename(columns = {"Count":str(count_date)})
    
    return clean_df

In [10]:
#apply to all dfs
march23_table_clean  = clean_table_counts(march23_table_counts_df)
apr23_table_clean = clean_table_counts(apr23_table_counts_df)
jul23_table_clean = clean_table_counts(jul23_table_counts_df)
aug23_table_clean = clean_table_counts(aug23_table_counts_df)
nov2324_table_clean = clean_table_counts(nov2324_table_counts_df)
nov2329_table_clean = clean_table_counts(nov2329_table_counts_df)
dec23_table_clean = clean_table_counts(dec23_table_counts_df)
jan24_table_clean = clean_table_counts(jan24_table_counts_df)
feb2401_table_clean = clean_table_counts(feb2401_table_counts_df)
feb2419_table_clean = clean_table_counts(feb2419_table_counts_df)
march24_table_clean = clean_table_counts(march24_table_counts_df)

In [11]:
#constructing a dataframe with all table counts
table_counts_df_1 = pd.merge(march23_table_clean, apr23_table_clean, on = "TableName", how = "inner") 
table_counts_df_2 = pd.merge(table_counts_df_1, jul23_table_clean, on = "TableName", how = "inner") 
table_counts_df_3 = pd.merge(table_counts_df_2, aug23_table_clean, on = "TableName", how = "inner") 
table_counts_df_4 = pd.merge(table_counts_df_3, nov2324_table_clean, on = "TableName", how = "inner") 
table_counts_df_5 = pd.merge(table_counts_df_4, nov2329_table_clean, on = "TableName", how = "inner")
table_counts_df_6 = pd.merge(table_counts_df_5, dec23_table_clean, on = "TableName", how = "inner") 
table_counts_df_7 = pd.merge(table_counts_df_6, jan24_table_clean, on = "TableName", how = "inner") 
table_counts_df_8 = pd.merge(table_counts_df_7, feb2401_table_clean, on = "TableName", how = "inner") 
table_counts_df_9 = pd.merge(table_counts_df_8, feb2419_table_clean, on = "TableName", how = "inner") 
all_table_counts_df = pd.merge(table_counts_df_9, march24_table_clean, on = "TableName", how = "inner")

In [12]:
all_table_counts_df.head()

,TableName,count_20230331,count_20230421,count_20230720,count_20230830,count_20231124,count_20231129,count_20231206,count_20240112,count_20240201,count_20240219,count_20240325
0,CDM_SOURCE,1,1,1,1,1,1,1,1,1,1,1
1,CONDITION_ERA,3719765,3750309,3752566,3753682,4197835,4052256,4052653,4256772,4336704,4341607,4348545
2,CONDITION_OCCURRENCE,3773735,3815270,3817738,3818928,4264191,4080750,4081162,4286860,4367805,4372796,4379860
3,DEATH,1473161,1473407,1473507,1473768,1474523,1474591,1474670,1490758,1495817,1496502,1497644
4,DEVICE_EXPOSURE,0,0,0,0,0,0,0,0,0,0,0

In [16]:
#count the days between each measurement
column_df = all_table_counts_df.columns
column_list = column_df.tolist()
#consider only columns that contain a date (all except the 1st)
column_list = column_list[1:]


#get from column names to date strings
date_list = []
for name in column_list:
    name = name.replace('count_', '')
    print(name)
    date_list.append(name)

date_list

20230331
20230421
20230720
20230830
20231124
20231129
20231206
20240112
20240201
20240219
20240325

['20230331',
 '20230421',
 '20230720',
 '20230830',
 '20231124',
 '20231129',
 '20231206',
 '20240112',
 '20240201',
 '20240219',
 '20240325']

Get from the dates of the results to an integer number of days between the dates and the date of the first result set (March 2023)

In [17]:
#get from date strings to dates

#get string version of dates
d0 = date_list[0]
d0 = datetime.datetime.strptime(str(d0),"%Y%m%d").date()
d1 = datetime.datetime.strptime(str(date_list[1]),"%Y%m%d").date()
delta1 = d1 - d0
day_difference1 = delta1.days

#for difference between first and d2 (third) date
d2 = datetime.datetime.strptime(str(date_list[2]),"%Y%m%d").date()
delta2 = d2 - d0
day_difference2 = delta2.days

#for d3 vs the first date
d3 = datetime.datetime.strptime(str(date_list[3]),"%Y%m%d").date()
delta3 = d3 - d0
day_difference3 = delta3.days


def day_difference(number : int):
    d0 = date_list[0]
    d0 = datetime.datetime.strptime(str(d0),"%Y%m%d").date()
    day = datetime.datetime.strptime(str(date_list[number]),"%Y%m%d").date()
    delta = day - d0
    day_difference = delta.days
    return day_difference
    

#get days between for the remaining result set (11 dates -> 10 differences)
day_difference4 = day_difference(4)
day_difference5 = day_difference(5)
day_difference6 = day_difference(6)
day_difference7 = day_difference(7)
day_difference8 = day_difference(8)
day_difference9 = day_difference(9)
day_difference10 = day_difference(10)


#put them into a list, with the first count at day 0
day_difference0 = 0
difference_list = [day_difference0, day_difference1, day_difference2, day_difference3, day_difference4, day_difference5,
                  day_difference6, day_difference7, day_difference8, day_difference9, day_difference10]
difference_list

[0, 21, 111, 152, 238, 243, 250, 287, 307, 325, 360]

### Confidence intervals for safe ranges of values

In [18]:
#create new columns with the difference in count divided by the number of days between the exports
for column in all_table_counts_df:
    print(column)
    current_column_name = column
    #initialize column_a and last day nr to allow a calculation of differences
    if column == "count_20230331":
        column_a = all_table_counts_df[column]
        index_nr = all_table_counts_df.columns.get_loc(column) -1
        last_day_nr = difference_list[index_nr]
    #select only the relevant columns for the difference calculation
    elif column != "TableName" and "count_20230331":
        #print(all_table_counts_df[column]) #this works
        #select the contents of the column
        column_b = all_table_counts_df[column]
        #make sure the new column has an intuitive name
        new_column_name = current_column_name.replace('count_','diff_')
        #create the new column with the count difference
        all_table_counts_df[str(new_column_name)] = column_b - column_a
        #print(all_table_counts_df[str(new_column_name)])
        #select the index of the current column and match to the index of the difference in days
        index_nr = all_table_counts_df.columns.get_loc(column) -1
        #get the nr of days between the counts
        days_since_0 = difference_list[index_nr]
        days_between = days_since_0 - last_day_nr
        print(days_between)
        #divide the difference by the number of days between
        all_table_counts_df[str(new_column_name)] = all_table_counts_df[str(new_column_name)] / days_between
        #set the column we just looked at as the new column for the next comparison
        column_a = column_b
        last_day_nr = days_since_0

TableName
count_20230331
count_20230421
21
count_20230720
90
count_20230830
41
count_20231124
86
count_20231129
5
count_20231206
7
count_20240112
37
count_20240201
20
count_20240219
18
count_20240325
35

In [19]:
#inspect the new df with the columns containing the differences / number of days between most recent observation 
print(all_table_counts_df.shape)
all_table_counts_df

(16, 22)

,TableName,count_20230331,count_20230421,count_20230720,count_20230830,count_20231124,count_20231129,count_20231206,count_20240112,count_20240201,...,diff_20230421,diff_20230720,diff_20230830,diff_20231124,diff_20231129,diff_20231206,diff_20240112,diff_20240201,diff_20240219,diff_20240325
0,CDM_SOURCE,1,1,1,1,1,1,1,1,1,...,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.00,0.000000,0.000000
1,CONDITION_ERA,3719765,3750309,3752566,3753682,4197835,4052256,4052653,4256772,4336704,...,1454.476190,25.077778,27.219512,5164.569767,-29115.8,56.714286,5516.729730,3996.60,272.388889,198.228571
2,CONDITION_OCCURRENCE,3773735,3815270,3817738,3818928,4264191,4080750,4081162,4286860,4367805,...,1977.857143,27.422222,29.024390,5177.476744,-36688.2,58.857143,5559.405405,4047.25,277.277778,201.828571
3,DEATH,1473161,1473407,1473507,1473768,1474523,1474591,1474670,1490758,1495817,...,11.714286,1.111111,6.365854,8.779070,13.6,11.285714,434.810811,252.95,38.055556,32.628571
4,DEVICE_EXPOSURE,0,0,0,0,0,0,0,0,0,...,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.00,0.000000,0.000000
5,DOSE_ERA,0,0,0,0,0,0,0,0,0,...,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.00,0.000000,0.000000
6,DRUG_ERA,803247,922244,926688,927747,932084,932467,932831,1036520,1041001,...,5666.523810,49.377778,25.829268,50.430233,76.6,52.000000,2802.405405,224.05,201.944444,152.342857
7,DRUG_EXPOSURE,1104574,1245311,1304035,1314188,1318738,1319147,1319525,1440227,1445869,...,6701.761905,652.488889,247.634146,52.906977,81.8,54.000000,3262.216216,282.10,229.833333,179.657143
8,EPISODE,5587312,5772838,5781263,5783305,5788997,5789538,5790109,6084669,6180422,...,8834.571429,93.611111,49.804878,66.186047,108.2,81.571429,7961.081081,4787.65,446.333333,323.228571
9,EPISODE_EVENT,31259659,33846008,33946099,33998987,35064939,34181821,34185384,35948492,36674327,...,123159.476190,1112.122222,1289.951220,12394.790698,-176623.6,509.000000,47651.567568,36291.75,20005.055556,1708.942857
10,MEASUREMENT,21429327,23730799,23759096,23438746,23454132,23134138,23136814,24286963,24780419,...,109593.904762,314.411111,-7813.414634,178.906977,-63998.8,382.285714,31085.108108,24672.80,19165.611111,1122.342857
11,OBSERVATION,537375,562916,563047,820226,1722496,1342377,1342482,1410965,1422758,...,1216.238095,1.455556,6272.658537,10491.511628,-76023.8,15.000000,1850.891892,589.65,99.166667,33.085714
12,OBSERVATION_PERIOD,2383484,2383827,2384097,2384330,2384687,2384775,2384829,2481791,2514888,...,16.333333,3.000000,5.682927,4.151163,17.6,7.714286,2620.594595,1654.85,102.944444,75.114286
13,PERSON,2383484,2383827,2384097,2384330,2384687,2384775,2384829,2481791,2514888,...,16.333333,3.000000,5.682927,4.151163,17.6,7.714286,2620.594595,1654.85,102.944444,75.114286
14,PROCEDURE_OCCURRENCE,4503171,4613908,4625536,4730521,5003188,5003406,5003689,5250847,5389052,...,5273.190476,129.200000,2560.609756,3170.546512,43.6,40.428571,6679.945946,6910.25,315.222222,235.628571
15,SPECIMEN,0,0,0,0,0,0,0,0,0,...,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.00,0.000000,0.000000

In [24]:
#select only the columns with differences for a new df -> change number to correspond with column index of diff_20230421
diff_table_counts_df = all_table_counts_df.iloc[:,12:]

#include the table names for clarity
diff_table_counts_df["TableName"] = all_table_counts_df["TableName"]
diff_table_counts_df

,diff_20230421,diff_20230720,diff_20230830,diff_20231124,diff_20231129,diff_20231206,diff_20240112,diff_20240201,diff_20240219,diff_20240325,TableName
0,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.00,0.000000,0.000000,CDM_SOURCE
1,1454.476190,25.077778,27.219512,5164.569767,-29115.8,56.714286,5516.729730,3996.60,272.388889,198.228571,CONDITION_ERA
2,1977.857143,27.422222,29.024390,5177.476744,-36688.2,58.857143,5559.405405,4047.25,277.277778,201.828571,CONDITION_OCCURRENCE
3,11.714286,1.111111,6.365854,8.779070,13.6,11.285714,434.810811,252.95,38.055556,32.628571,DEATH
4,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.00,0.000000,0.000000,DEVICE_EXPOSURE
5,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.00,0.000000,0.000000,DOSE_ERA
6,5666.523810,49.377778,25.829268,50.430233,76.6,52.000000,2802.405405,224.05,201.944444,152.342857,DRUG_ERA
7,6701.761905,652.488889,247.634146,52.906977,81.8,54.000000,3262.216216,282.10,229.833333,179.657143,DRUG_EXPOSURE
8,8834.571429,93.611111,49.804878,66.186047,108.2,81.571429,7961.081081,4787.65,446.333333,323.228571,EPISODE
9,123159.476190,1112.122222,1289.951220,12394.790698,-176623.6,509.000000,47651.567568,36291.75,20005.055556,1708.942857,EPISODE_EVENT
10,109593.904762,314.411111,-7813.414634,178.906977,-63998.8,382.285714,31085.108108,24672.80,19165.611111,1122.342857,MEASUREMENT
11,1216.238095,1.455556,6272.658537,10491.511628,-76023.8,15.000000,1850.891892,589.65,99.166667,33.085714,OBSERVATION
12,16.333333,3.000000,5.682927,4.151163,17.6,7.714286,2620.594595,1654.85,102.944444,75.114286,OBSERVATION_PERIOD
13,16.333333,3.000000,5.682927,4.151163,17.6,7.714286,2620.594595,1654.85,102.944444,75.114286,PERSON
14,5273.190476,129.200000,2560.609756,3170.546512,43.6,40.428571,6679.945946,6910.25,315.222222,235.628571,PROCEDURE_OCCURRENCE
15,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.00,0.000000,0.000000,SPECIMEN

#### Transpose the table to get the results per table

In [25]:
#transpose table to allow pandas statistics
diff_counts_per_table = diff_table_counts_df.transpose()

#turn table names into the column names
table_names = list(diff_table_counts_df["TableName"])
diff_counts_per_table = diff_counts_per_table.rename(columns = {0:table_names[0], 1:table_names[1], 2:table_names[2], 
                                                               3:table_names[3], 4:table_names[4], 5:table_names[5],
                                                               6:table_names[6], 7:table_names[7], 8:table_names[8],
                                                               9:table_names[9], 10:table_names[10], 11:table_names[11],
                                                               12:table_names[12], 13:table_names[13], 14:table_names[14],
                                                               15:table_names[15]})
diff_counts_per_table

,CDM_SOURCE,CONDITION_ERA,CONDITION_OCCURRENCE,DEATH,DEVICE_EXPOSURE,DOSE_ERA,DRUG_ERA,DRUG_EXPOSURE,EPISODE,EPISODE_EVENT,MEASUREMENT,OBSERVATION,OBSERVATION_PERIOD,PERSON,PROCEDURE_OCCURRENCE,SPECIMEN
diff_20230421,0.0,1454.47619,1977.857143,11.714286,0.0,0.0,5666.52381,6701.761905,8834.571429,123159.47619,109593.904762,1216.238095,16.333333,16.333333,5273.190476,0.0
diff_20230720,0.0,25.077778,27.422222,1.111111,0.0,0.0,49.377778,652.488889,93.611111,1112.122222,314.411111,1.455556,3.0,3.0,129.2,0.0
diff_20230830,0.0,27.219512,29.02439,6.365854,0.0,0.0,25.829268,247.634146,49.804878,1289.95122,-7813.414634,6272.658537,5.682927,5.682927,2560.609756,0.0
diff_20231124,0.0,5164.569767,5177.476744,8.77907,0.0,0.0,50.430233,52.906977,66.186047,12394.790698,178.906977,10491.511628,4.151163,4.151163,3170.546512,0.0
diff_20231129,0.0,-29115.8,-36688.2,13.6,0.0,0.0,76.6,81.8,108.2,-176623.6,-63998.8,-76023.8,17.6,17.6,43.6,0.0
diff_20231206,0.0,56.714286,58.857143,11.285714,0.0,0.0,52.0,54.0,81.571429,509.0,382.285714,15.0,7.714286,7.714286,40.428571,0.0
diff_20240112,0.0,5516.72973,5559.405405,434.810811,0.0,0.0,2802.405405,3262.216216,7961.081081,47651.567568,31085.108108,1850.891892,2620.594595,2620.594595,6679.945946,0.0
diff_20240201,0.0,3996.6,4047.25,252.95,0.0,0.0,224.05,282.1,4787.65,36291.75,24672.8,589.65,1654.85,1654.85,6910.25,0.0
diff_20240219,0.0,272.388889,277.277778,38.055556,0.0,0.0,201.944444,229.833333,446.333333,20005.055556,19165.611111,99.166667,102.944444,102.944444,315.222222,0.0
diff_20240325,0.0,198.228571,201.828571,32.628571,0.0,0.0,152.342857,179.657143,323.228571,1708.942857,1122.342857,33.085714,75.114286,75.114286,235.628571,0.0
TableName,CDM_SOURCE,CONDITION_ERA,CONDITION_OCCURRENCE,DEATH,DEVICE_EXPOSURE,DOSE_ERA,DRUG_ERA,DRUG_EXPOSURE,EPISODE,EPISODE_EVENT,MEASUREMENT,OBSERVATION,OBSERVATION_PERIOD,PERSON,PROCEDURE_OCCURRENCE,SPECIMEN

In [27]:
#drop the row with TableNames
print(diff_counts_per_table.shape)
#change the range here if more results sets have been added, should consider the shape(x,y) -> range[0:x-1]
diff_counts_per_table = diff_counts_per_table[0:10]
diff_counts_per_table

(11, 16)

,CDM_SOURCE,CONDITION_ERA,CONDITION_OCCURRENCE,DEATH,DEVICE_EXPOSURE,DOSE_ERA,DRUG_ERA,DRUG_EXPOSURE,EPISODE,EPISODE_EVENT,MEASUREMENT,OBSERVATION,OBSERVATION_PERIOD,PERSON,PROCEDURE_OCCURRENCE,SPECIMEN
diff_20230421,0.0,1454.47619,1977.857143,11.714286,0.0,0.0,5666.52381,6701.761905,8834.571429,123159.47619,109593.904762,1216.238095,16.333333,16.333333,5273.190476,0.0
diff_20230720,0.0,25.077778,27.422222,1.111111,0.0,0.0,49.377778,652.488889,93.611111,1112.122222,314.411111,1.455556,3.0,3.0,129.2,0.0
diff_20230830,0.0,27.219512,29.02439,6.365854,0.0,0.0,25.829268,247.634146,49.804878,1289.95122,-7813.414634,6272.658537,5.682927,5.682927,2560.609756,0.0
diff_20231124,0.0,5164.569767,5177.476744,8.77907,0.0,0.0,50.430233,52.906977,66.186047,12394.790698,178.906977,10491.511628,4.151163,4.151163,3170.546512,0.0
diff_20231129,0.0,-29115.8,-36688.2,13.6,0.0,0.0,76.6,81.8,108.2,-176623.6,-63998.8,-76023.8,17.6,17.6,43.6,0.0
diff_20231206,0.0,56.714286,58.857143,11.285714,0.0,0.0,52.0,54.0,81.571429,509.0,382.285714,15.0,7.714286,7.714286,40.428571,0.0
diff_20240112,0.0,5516.72973,5559.405405,434.810811,0.0,0.0,2802.405405,3262.216216,7961.081081,47651.567568,31085.108108,1850.891892,2620.594595,2620.594595,6679.945946,0.0
diff_20240201,0.0,3996.6,4047.25,252.95,0.0,0.0,224.05,282.1,4787.65,36291.75,24672.8,589.65,1654.85,1654.85,6910.25,0.0
diff_20240219,0.0,272.388889,277.277778,38.055556,0.0,0.0,201.944444,229.833333,446.333333,20005.055556,19165.611111,99.166667,102.944444,102.944444,315.222222,0.0
diff_20240325,0.0,198.228571,201.828571,32.628571,0.0,0.0,152.342857,179.657143,323.228571,1708.942857,1122.342857,33.085714,75.114286,75.114286,235.628571,0.0

#### Confidence Interval per table

- In the initial analysis we discussed visualisations of the slope for count differrences and identified changes that were due to the ETL 
- Below we use table-specific preprocessing: removing rows where the ETL changed in a way that influenced the table
- Calculated confidence intervals for each table for non-suspicious range of change. 
- Determined in a discussion which percentage (e.g. 90% vs 95%) confidence interval was used and discussed which values should or should not be flagged (e.g. no table should have a negative change)
- For the OBSERVATION table we calculated a confidence interval for suspicious ranges instead of non-suspicious, since there were too few samples to consider the non-suspicious CI

In [28]:
## CONDITION_ERA & CONDITION OCCURRENCE

#only considering periods with "normal change" (which means no changes were made to the ETL)
condition_era_occ = diff_counts_per_table.copy()
#drop rows with diff to april, no 24, nov 29, jan and the first one of feb 2024
condition_era_occ = condition_era_occ.iloc[[1,2,5,8,9]]

condition_era_occ

,CDM_SOURCE,CONDITION_ERA,CONDITION_OCCURRENCE,DEATH,DEVICE_EXPOSURE,DOSE_ERA,DRUG_ERA,DRUG_EXPOSURE,EPISODE,EPISODE_EVENT,MEASUREMENT,OBSERVATION,OBSERVATION_PERIOD,PERSON,PROCEDURE_OCCURRENCE,SPECIMEN
diff_20230720,0.0,25.077778,27.422222,1.111111,0.0,0.0,49.377778,652.488889,93.611111,1112.122222,314.411111,1.455556,3.0,3.0,129.2,0.0
diff_20230830,0.0,27.219512,29.02439,6.365854,0.0,0.0,25.829268,247.634146,49.804878,1289.95122,-7813.414634,6272.658537,5.682927,5.682927,2560.609756,0.0
diff_20231206,0.0,56.714286,58.857143,11.285714,0.0,0.0,52.0,54.0,81.571429,509.0,382.285714,15.0,7.714286,7.714286,40.428571,0.0
diff_20240219,0.0,272.388889,277.277778,38.055556,0.0,0.0,201.944444,229.833333,446.333333,20005.055556,19165.611111,99.166667,102.944444,102.944444,315.222222,0.0
diff_20240325,0.0,198.228571,201.828571,32.628571,0.0,0.0,152.342857,179.657143,323.228571,1708.942857,1122.342857,33.085714,75.114286,75.114286,235.628571,0.0

In [82]:
# Calculate the mean and standard error of the mean (SEM)
mean = condition_era_occ["CONDITION_ERA"].mean()
sem = stats.sem(condition_era_occ["CONDITION_ERA"])

# Calculate the confidence interval using the t-distribution
confidence_level = 0.999
degrees_freedom = len(condition_era_occ["CONDITION_ERA"]) - 1
confidence_interval = stats.t.interval(confidence_level, degrees_freedom, loc=mean, scale=sem)

print("99.9% Confidence Interval for column '{}':".format("CONDITION_ERA"))
print("Lower Bound:", confidence_interval[0])
print("Upper Bound:", confidence_interval[1])

99.9% Confidence Interval for column 'CONDITION_ERA':
Lower Bound: -318.3724462708874
Upper Bound: 550.2240606727582

In [83]:
# Calculate the mean and standard error of the mean (SEM)
mean = condition_era_occ["CONDITION_OCCURRENCE"].mean()
sem = stats.sem(condition_era_occ["CONDITION_OCCURRENCE"])

# Calculate the confidence interval using the t-distribution
confidence_level = 0.999
degrees_freedom = len(condition_era_occ["CONDITION_OCCURRENCE"]) - 1
confidence_interval = stats.t.interval(confidence_level, degrees_freedom, loc=mean, scale=sem)

print("99.9% Confidence Interval for column '{}':".format("CONDITION_OCCURRENCE"))
print("Lower Bound:", confidence_interval[0])
print("Upper Bound:", confidence_interval[1])

99.9% Confidence Interval for column 'CONDITION_OCCURRENCE':
Lower Bound: -320.2079910287143
Upper Bound: 557.9720328405737

In [34]:
##DEATH table

#only considering periods with "normal change" (which means no persons were added to the CDM)
death_analysis = diff_counts_per_table.copy()
#drop rows with diagnoses of 2022 added and DCIS (jan and first of feb 24)
death_analysis = death_analysis.iloc[[0,1,2,3,4,5,8,9]]

death_analysis

,CDM_SOURCE,CONDITION_ERA,CONDITION_OCCURRENCE,DEATH,DEVICE_EXPOSURE,DOSE_ERA,DRUG_ERA,DRUG_EXPOSURE,EPISODE,EPISODE_EVENT,MEASUREMENT,OBSERVATION,OBSERVATION_PERIOD,PERSON,PROCEDURE_OCCURRENCE,SPECIMEN
diff_20230421,0.0,1454.47619,1977.857143,11.714286,0.0,0.0,5666.52381,6701.761905,8834.571429,123159.47619,109593.904762,1216.238095,16.333333,16.333333,5273.190476,0.0
diff_20230720,0.0,25.077778,27.422222,1.111111,0.0,0.0,49.377778,652.488889,93.611111,1112.122222,314.411111,1.455556,3.0,3.0,129.2,0.0
diff_20230830,0.0,27.219512,29.02439,6.365854,0.0,0.0,25.829268,247.634146,49.804878,1289.95122,-7813.414634,6272.658537,5.682927,5.682927,2560.609756,0.0
diff_20231124,0.0,5164.569767,5177.476744,8.77907,0.0,0.0,50.430233,52.906977,66.186047,12394.790698,178.906977,10491.511628,4.151163,4.151163,3170.546512,0.0
diff_20231129,0.0,-29115.8,-36688.2,13.6,0.0,0.0,76.6,81.8,108.2,-176623.6,-63998.8,-76023.8,17.6,17.6,43.6,0.0
diff_20231206,0.0,56.714286,58.857143,11.285714,0.0,0.0,52.0,54.0,81.571429,509.0,382.285714,15.0,7.714286,7.714286,40.428571,0.0
diff_20240219,0.0,272.388889,277.277778,38.055556,0.0,0.0,201.944444,229.833333,446.333333,20005.055556,19165.611111,99.166667,102.944444,102.944444,315.222222,0.0
diff_20240325,0.0,198.228571,201.828571,32.628571,0.0,0.0,152.342857,179.657143,323.228571,1708.942857,1122.342857,33.085714,75.114286,75.114286,235.628571,0.0

In [38]:
# Calculate the mean and standard error of the mean (SEM)
mean = death_analysis["DEATH"].mean()
sem = stats.sem(death_analysis["DEATH"])

# Calculate the confidence interval using the t-distribution
confidence_level = 0.999
degrees_freedom = len(death_analysis["DEATH"]) - 1
confidence_interval = stats.t.interval(confidence_level, degrees_freedom, loc=mean, scale=sem)

print("99.9% Confidence Interval for column '{}':".format("DEATH"))
print("Lower Bound:", confidence_interval[0])
print("Upper Bound:", confidence_interval[1]) #this range is for not flagging the one for Feb 19th

99.9% Confidence Interval for column 'DEATH':
Lower Bound: -9.312734565390421
Upper Bound: 40.19777494569503

In [39]:
## DRUG_ERA & DRUG_ EXPOSURE

#only considering periods with no ETL changes (that would be of influence)
drug_analysis = diff_counts_per_table.copy()
#drop rows with differences in 2024
drug_analysis = drug_analysis.iloc[[3,4,5,8,9]]

drug_analysis

,CDM_SOURCE,CONDITION_ERA,CONDITION_OCCURRENCE,DEATH,DEVICE_EXPOSURE,DOSE_ERA,DRUG_ERA,DRUG_EXPOSURE,EPISODE,EPISODE_EVENT,MEASUREMENT,OBSERVATION,OBSERVATION_PERIOD,PERSON,PROCEDURE_OCCURRENCE,SPECIMEN
diff_20231124,0.0,5164.569767,5177.476744,8.77907,0.0,0.0,50.430233,52.906977,66.186047,12394.790698,178.906977,10491.511628,4.151163,4.151163,3170.546512,0.0
diff_20231129,0.0,-29115.8,-36688.2,13.6,0.0,0.0,76.6,81.8,108.2,-176623.6,-63998.8,-76023.8,17.6,17.6,43.6,0.0
diff_20231206,0.0,56.714286,58.857143,11.285714,0.0,0.0,52.0,54.0,81.571429,509.0,382.285714,15.0,7.714286,7.714286,40.428571,0.0
diff_20240219,0.0,272.388889,277.277778,38.055556,0.0,0.0,201.944444,229.833333,446.333333,20005.055556,19165.611111,99.166667,102.944444,102.944444,315.222222,0.0
diff_20240325,0.0,198.228571,201.828571,32.628571,0.0,0.0,152.342857,179.657143,323.228571,1708.942857,1122.342857,33.085714,75.114286,75.114286,235.628571,0.0

In [48]:
# Calculate the mean and standard error of the mean (SEM)
mean = drug_analysis["DRUG_ERA"].mean()
sem = stats.sem(drug_analysis["DRUG_ERA"])

# Calculate the confidence interval using the t-distribution
confidence_level = 0.975
degrees_freedom = len(drug_analysis["DRUG_ERA"]) - 1
confidence_interval = stats.t.interval(confidence_level, degrees_freedom, loc=mean, scale=sem)

print("97.5% Confidence Interval for column '{}':".format("DRUG_ERA"))
print("Lower Bound:", confidence_interval[0])
print("Upper Bound:", confidence_interval[1]) #224.05 should be flagged, 201 should not

97.5% Confidence Interval for column 'DRUG_ERA':
Lower Bound: 1.164898044744092
Upper Bound: 212.16211561343252

In [50]:
# Calculate the mean and standard error of the mean (SEM)
mean = drug_analysis["DRUG_EXPOSURE"].mean()
sem = stats.sem(drug_analysis["DRUG_EXPOSURE"])

# Calculate the confidence interval using the t-distribution
confidence_level = 0.975
degrees_freedom = len(drug_analysis["DRUG_EXPOSURE"]) - 1
confidence_interval = stats.t.interval(confidence_level, degrees_freedom, loc=mean, scale=sem)

print("97.5% Confidence Interval for column '{}':".format("DRUG_EXPOSURE"))
print("Lower Bound:", confidence_interval[0])
print("Upper Bound:", confidence_interval[1]) #282.1 should be flagged, 229 should not

97.5% Confidence Interval for column 'DRUG_EXPOSURE':
Lower Bound: -6.239777948018741
Upper Bound: 245.51875912188382

In [51]:
##EPISODE & EPISODE_EVENT

#only considering periods with no ETL changes (that would be of influence)
episode_analysis = diff_counts_per_table.copy()
#drop rows with differences in 2024
episode_analysis = episode_analysis.iloc[[1,2,3,4,5,8,9]]
episode_analysis

,CDM_SOURCE,CONDITION_ERA,CONDITION_OCCURRENCE,DEATH,DEVICE_EXPOSURE,DOSE_ERA,DRUG_ERA,DRUG_EXPOSURE,EPISODE,EPISODE_EVENT,MEASUREMENT,OBSERVATION,OBSERVATION_PERIOD,PERSON,PROCEDURE_OCCURRENCE,SPECIMEN
diff_20230720,0.0,25.077778,27.422222,1.111111,0.0,0.0,49.377778,652.488889,93.611111,1112.122222,314.411111,1.455556,3.0,3.0,129.2,0.0
diff_20230830,0.0,27.219512,29.02439,6.365854,0.0,0.0,25.829268,247.634146,49.804878,1289.95122,-7813.414634,6272.658537,5.682927,5.682927,2560.609756,0.0
diff_20231124,0.0,5164.569767,5177.476744,8.77907,0.0,0.0,50.430233,52.906977,66.186047,12394.790698,178.906977,10491.511628,4.151163,4.151163,3170.546512,0.0
diff_20231129,0.0,-29115.8,-36688.2,13.6,0.0,0.0,76.6,81.8,108.2,-176623.6,-63998.8,-76023.8,17.6,17.6,43.6,0.0
diff_20231206,0.0,56.714286,58.857143,11.285714,0.0,0.0,52.0,54.0,81.571429,509.0,382.285714,15.0,7.714286,7.714286,40.428571,0.0
diff_20240219,0.0,272.388889,277.277778,38.055556,0.0,0.0,201.944444,229.833333,446.333333,20005.055556,19165.611111,99.166667,102.944444,102.944444,315.222222,0.0
diff_20240325,0.0,198.228571,201.828571,32.628571,0.0,0.0,152.342857,179.657143,323.228571,1708.942857,1122.342857,33.085714,75.114286,75.114286,235.628571,0.0

In [56]:
# Calculate the mean and standard error of the mean (SEM)
mean = episode_analysis["EPISODE"].mean()
sem = stats.sem(episode_analysis["EPISODE"])

# Calculate the confidence interval using the t-distribution
confidence_level = 0.999
degrees_freedom = len(episode_analysis["EPISODE"]) - 1
confidence_interval = stats.t.interval(confidence_level, degrees_freedom, loc=mean, scale=sem)

print("99.9% Confidence Interval for column '{}':".format("EPISODE"))
print("Lower Bound:", confidence_interval[0])
print("Upper Bound:", confidence_interval[1]) #for not flagging Feb 19th

99.9% Confidence Interval for column 'EPISODE':
Lower Bound: -180.06815043967174
Upper Bound: 514.0496844410657

In [57]:
#MEASUREMENT

#only considering periods with no ETL changes (that would be of influence)
measurement_stable = diff_counts_per_table.copy()
#drop rows with differences in 2024
measurement_stable = measurement_stable.iloc[[1, 3, 5, 8, 9]] #is there a different reason to not include Feb 19th?
measurement_stable

,CDM_SOURCE,CONDITION_ERA,CONDITION_OCCURRENCE,DEATH,DEVICE_EXPOSURE,DOSE_ERA,DRUG_ERA,DRUG_EXPOSURE,EPISODE,EPISODE_EVENT,MEASUREMENT,OBSERVATION,OBSERVATION_PERIOD,PERSON,PROCEDURE_OCCURRENCE,SPECIMEN
diff_20230720,0.0,25.077778,27.422222,1.111111,0.0,0.0,49.377778,652.488889,93.611111,1112.122222,314.411111,1.455556,3.0,3.0,129.2,0.0
diff_20231124,0.0,5164.569767,5177.476744,8.77907,0.0,0.0,50.430233,52.906977,66.186047,12394.790698,178.906977,10491.511628,4.151163,4.151163,3170.546512,0.0
diff_20231206,0.0,56.714286,58.857143,11.285714,0.0,0.0,52.0,54.0,81.571429,509.0,382.285714,15.0,7.714286,7.714286,40.428571,0.0
diff_20240219,0.0,272.388889,277.277778,38.055556,0.0,0.0,201.944444,229.833333,446.333333,20005.055556,19165.611111,99.166667,102.944444,102.944444,315.222222,0.0
diff_20240325,0.0,198.228571,201.828571,32.628571,0.0,0.0,152.342857,179.657143,323.228571,1708.942857,1122.342857,33.085714,75.114286,75.114286,235.628571,0.0

In [81]:
# Calculate the mean and standard error of the mean (SEM)
mean = measurement_stable["MEASUREMENT"].mean()
sem = stats.sem(measurement_stable["MEASUREMENT"])

# Calculate the confidence interval using the t-distribution
confidence_level = 0.99
degrees_freedom = len(measurement_stable["MEASUREMENT"]) - 1
confidence_interval = stats.t.interval(confidence_level, degrees_freedom, loc=mean, scale=sem)

print("99% Confidence Interval for column '{}':".format("MEASUREMENT"))
print("Lower Bound:", confidence_interval[0])
print("Upper Bound:", confidence_interval[1]) #how certain do we want to be that changes such as with DCIS would be flagged

99% Confidence Interval for column 'MEASUREMENT':
Lower Bound: -12972.011447457364
Upper Bound: 21437.434555615357

In [59]:
##OBSERVATION

#only considering periods with no ETL changes (that would be of influence)
obsv_stable = diff_counts_per_table.copy()
obsv_stable = obsv_stable.iloc[[1, 5, 8, 9]]
obsv_stable

,CDM_SOURCE,CONDITION_ERA,CONDITION_OCCURRENCE,DEATH,DEVICE_EXPOSURE,DOSE_ERA,DRUG_ERA,DRUG_EXPOSURE,EPISODE,EPISODE_EVENT,MEASUREMENT,OBSERVATION,OBSERVATION_PERIOD,PERSON,PROCEDURE_OCCURRENCE,SPECIMEN
diff_20230720,0.0,25.077778,27.422222,1.111111,0.0,0.0,49.377778,652.488889,93.611111,1112.122222,314.411111,1.455556,3.0,3.0,129.2,0.0
diff_20231206,0.0,56.714286,58.857143,11.285714,0.0,0.0,52.0,54.0,81.571429,509.0,382.285714,15.0,7.714286,7.714286,40.428571,0.0
diff_20240219,0.0,272.388889,277.277778,38.055556,0.0,0.0,201.944444,229.833333,446.333333,20005.055556,19165.611111,99.166667,102.944444,102.944444,315.222222,0.0
diff_20240325,0.0,198.228571,201.828571,32.628571,0.0,0.0,152.342857,179.657143,323.228571,1708.942857,1122.342857,33.085714,75.114286,75.114286,235.628571,0.0

In [77]:
# Calculate the mean and standard error of the mean (SEM)
mean = obsv_stable["OBSERVATION"].mean()
sem = stats.sem(obsv_stable["OBSERVATION"])

# Calculate the confidence interval using the t-distribution
confidence_level = 0.999
degrees_freedom = len(obsv_stable["OBSERVATION"]) - 1
confidence_interval = stats.t.interval(confidence_level, degrees_freedom, loc=mean, scale=sem)

print("99.9% Confidence Interval for column '{}':".format("OBSERVATION"))
print("Lower Bound:", confidence_interval[0])
print("Upper Bound:", confidence_interval[1])

99.9% Confidence Interval for column 'OBSERVATION':
Lower Bound: -242.69251962325134
Upper Bound: 317.0464878772301

In [66]:
##OBSERVATION_PERIOD

#only considering periods with no ETL changes (that would be of influence)
obsv_period = diff_counts_per_table.copy()
obsv_period = obsv_period.iloc[[0,1,2,3,4,5,8,9]]
obsv_period

,CDM_SOURCE,CONDITION_ERA,CONDITION_OCCURRENCE,DEATH,DEVICE_EXPOSURE,DOSE_ERA,DRUG_ERA,DRUG_EXPOSURE,EPISODE,EPISODE_EVENT,MEASUREMENT,OBSERVATION,OBSERVATION_PERIOD,PERSON,PROCEDURE_OCCURRENCE,SPECIMEN
diff_20230421,0.0,1454.47619,1977.857143,11.714286,0.0,0.0,5666.52381,6701.761905,8834.571429,123159.47619,109593.904762,1216.238095,16.333333,16.333333,5273.190476,0.0
diff_20230720,0.0,25.077778,27.422222,1.111111,0.0,0.0,49.377778,652.488889,93.611111,1112.122222,314.411111,1.455556,3.0,3.0,129.2,0.0
diff_20230830,0.0,27.219512,29.02439,6.365854,0.0,0.0,25.829268,247.634146,49.804878,1289.95122,-7813.414634,6272.658537,5.682927,5.682927,2560.609756,0.0
diff_20231124,0.0,5164.569767,5177.476744,8.77907,0.0,0.0,50.430233,52.906977,66.186047,12394.790698,178.906977,10491.511628,4.151163,4.151163,3170.546512,0.0
diff_20231129,0.0,-29115.8,-36688.2,13.6,0.0,0.0,76.6,81.8,108.2,-176623.6,-63998.8,-76023.8,17.6,17.6,43.6,0.0
diff_20231206,0.0,56.714286,58.857143,11.285714,0.0,0.0,52.0,54.0,81.571429,509.0,382.285714,15.0,7.714286,7.714286,40.428571,0.0
diff_20240219,0.0,272.388889,277.277778,38.055556,0.0,0.0,201.944444,229.833333,446.333333,20005.055556,19165.611111,99.166667,102.944444,102.944444,315.222222,0.0
diff_20240325,0.0,198.228571,201.828571,32.628571,0.0,0.0,152.342857,179.657143,323.228571,1708.942857,1122.342857,33.085714,75.114286,75.114286,235.628571,0.0

In [64]:
# Calculate the mean and standard error of the mean (SEM)
mean = obsv_period["OBSERVATION_PERIOD"].mean()
sem = stats.sem(obsv_period["OBSERVATION_PERIOD"])

# Calculate the confidence interval using the t-distribution
confidence_level = 0.999
degrees_freedom = len(obsv_period["OBSERVATION_PERIOD"]) - 1
confidence_interval = stats.t.interval(confidence_level, degrees_freedom, loc=mean, scale=sem)

print("99.9% Confidence Interval for column '{}':".format("OBSERVATION_PERIOD"))
print("Lower Bound:", confidence_interval[0])
print("Upper Bound:", confidence_interval[1]) #Feb 19th would still be flagged

99.9% Confidence Interval for column 'OBSERVATION_PERIOD':
Lower Bound: -43.82757080660271
Upper Bound: 101.9626805131829

In [67]:
##PERSON

#only considering periods with no ETL changes (that would be of influence)
person_stable = diff_counts_per_table.copy()
person_stable = person_stable.iloc[[0,1,2,3,4,5,8,9]]
person_stable

,CDM_SOURCE,CONDITION_ERA,CONDITION_OCCURRENCE,DEATH,DEVICE_EXPOSURE,DOSE_ERA,DRUG_ERA,DRUG_EXPOSURE,EPISODE,EPISODE_EVENT,MEASUREMENT,OBSERVATION,OBSERVATION_PERIOD,PERSON,PROCEDURE_OCCURRENCE,SPECIMEN
diff_20230421,0.0,1454.47619,1977.857143,11.714286,0.0,0.0,5666.52381,6701.761905,8834.571429,123159.47619,109593.904762,1216.238095,16.333333,16.333333,5273.190476,0.0
diff_20230720,0.0,25.077778,27.422222,1.111111,0.0,0.0,49.377778,652.488889,93.611111,1112.122222,314.411111,1.455556,3.0,3.0,129.2,0.0
diff_20230830,0.0,27.219512,29.02439,6.365854,0.0,0.0,25.829268,247.634146,49.804878,1289.95122,-7813.414634,6272.658537,5.682927,5.682927,2560.609756,0.0
diff_20231124,0.0,5164.569767,5177.476744,8.77907,0.0,0.0,50.430233,52.906977,66.186047,12394.790698,178.906977,10491.511628,4.151163,4.151163,3170.546512,0.0
diff_20231129,0.0,-29115.8,-36688.2,13.6,0.0,0.0,76.6,81.8,108.2,-176623.6,-63998.8,-76023.8,17.6,17.6,43.6,0.0
diff_20231206,0.0,56.714286,58.857143,11.285714,0.0,0.0,52.0,54.0,81.571429,509.0,382.285714,15.0,7.714286,7.714286,40.428571,0.0
diff_20240219,0.0,272.388889,277.277778,38.055556,0.0,0.0,201.944444,229.833333,446.333333,20005.055556,19165.611111,99.166667,102.944444,102.944444,315.222222,0.0
diff_20240325,0.0,198.228571,201.828571,32.628571,0.0,0.0,152.342857,179.657143,323.228571,1708.942857,1122.342857,33.085714,75.114286,75.114286,235.628571,0.0

In [69]:
# Calculate the mean and standard error of the mean (SEM)
mean = person_stable["PERSON"].mean()
sem = stats.sem(person_stable["PERSON"])

# Calculate the confidence interval using the t-distribution
confidence_level = 0.999
degrees_freedom = len(person_stable["PERSON"]) - 1
confidence_interval = stats.t.interval(confidence_level, degrees_freedom, loc=mean, scale=sem)

print("99.9% Confidence Interval for column '{}':".format("PERSON"))
print("Lower Bound:", confidence_interval[0])
print("Upper Bound:", confidence_interval[1]) #Feb 19th would still be flagged

99.9% Confidence Interval for column 'PERSON':
Lower Bound: -43.82757080660271
Upper Bound: 101.9626805131829

In [70]:
##PROCEDURE_OCCURRENCE

#only considering periods with no ETL changes (that would be of influence)
pro_occ_stable = diff_counts_per_table.copy()
pro_occ_stable = pro_occ_stable.iloc[[1,4,5,8,9]]
pro_occ_stable

,CDM_SOURCE,CONDITION_ERA,CONDITION_OCCURRENCE,DEATH,DEVICE_EXPOSURE,DOSE_ERA,DRUG_ERA,DRUG_EXPOSURE,EPISODE,EPISODE_EVENT,MEASUREMENT,OBSERVATION,OBSERVATION_PERIOD,PERSON,PROCEDURE_OCCURRENCE,SPECIMEN
diff_20230720,0.0,25.077778,27.422222,1.111111,0.0,0.0,49.377778,652.488889,93.611111,1112.122222,314.411111,1.455556,3.0,3.0,129.2,0.0
diff_20231129,0.0,-29115.8,-36688.2,13.6,0.0,0.0,76.6,81.8,108.2,-176623.6,-63998.8,-76023.8,17.6,17.6,43.6,0.0
diff_20231206,0.0,56.714286,58.857143,11.285714,0.0,0.0,52.0,54.0,81.571429,509.0,382.285714,15.0,7.714286,7.714286,40.428571,0.0
diff_20240219,0.0,272.388889,277.277778,38.055556,0.0,0.0,201.944444,229.833333,446.333333,20005.055556,19165.611111,99.166667,102.944444,102.944444,315.222222,0.0
diff_20240325,0.0,198.228571,201.828571,32.628571,0.0,0.0,152.342857,179.657143,323.228571,1708.942857,1122.342857,33.085714,75.114286,75.114286,235.628571,0.0

In [75]:
# Calculate the mean and standard error of the mean (SEM)
mean = pro_occ_stable["PROCEDURE_OCCURRENCE"].mean()
sem = stats.sem(pro_occ_stable["PROCEDURE_OCCURRENCE"])

# Calculate the confidence interval using the t-distribution
confidence_level = 0.999
degrees_freedom = len(pro_occ_stable["PROCEDURE_OCCURRENCE"]) - 1
confidence_interval = stats.t.interval(confidence_level, degrees_freedom, loc=mean, scale=sem)

print("99.9% Confidence Interval for column '{}':".format("PROCEDURE_OCCURRENCE"))
print("Lower Bound:", confidence_interval[0])
print("Upper Bound:", confidence_interval[1])

99.9% Confidence Interval for column 'PROCEDURE_OCCURRENCE':
Lower Bound: -312.261926186935
Upper Bound: 617.8936722186945